version: '3'

services:
    db:
        container_name: db
        image: mysql:5.7.22
        command: mysqld --sql_mode=""
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: application
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app_network

    app:
        container_name: app
        build: ./.docker/php
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - app_network

    nginx:
        container_name: nginx
        build: ./.docker/nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
        depends_on:
            - app
        networks:
            - app_network
    
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - "6379:6379"
        networks: 
            - app_network

networks:
    app_network:
        driver: bridge